export const fieldLabels: Record<string, string> = {
  fullName: "ПІБ",
  rank: "Звання",
  position: "Посада",
  unit: "Підрозділ",
  status: "Статус",
  birthDate: "Дата народження",
  phone: "Телефон",
  email: "Email",
  experience: "Досвід (років)",
  missions: "Кількість виходів",
  lastActiveDays: "Остання активність (днів)",
  photo: "Фото",
  name: "Назва",
  type: "Тип",
  serialNumber: "Серійний номер",
  issuedDate: "Дата видачі",
  condition: "Діагноз",
  diagnosisDate: "Дата діагнозу",
  notes: "Примітки",
  description: "Опис",
  date: "Дата",
  startDate: "Дата початку",
  endDate: "Дата закінчення",
  height: "Зріст",
  chest: "Обхват грудей",
  waist: "Обхват талії",
  shoes: "Розмір взуття",
  headgear: "Розмір головного убору",
  uniform: "Розмір форми",
  birthPlace: "Місце народження",
  passport: "Паспорт",
  passportIssued: "Паспорт видано",
  tin: "РНОКПП",
  militaryId: "Військовий квиток",
  militaryIdIssued: "Військовий квиток видано",
  ubd: "УБД",
  ubdDate: "Дата УБД",
  serviceUnit: "Частина",
  serviceYears: "Роки служби",
  civilianJob: "Цивільна спеціальність",
  education: "Освіта",
  actualAddress: "Фактична адреса",
  registrationAddress: "Адреса реєстрації",
  driverLicense: "Посвідчення водія",
  criminalRecord: "Судимість",
  policeRecords: "Облік в поліції",
  family: "Склад сім'ї",
  relativePhones: "Телефони рідних",
  personalOrder: "Особиста справа №",
  conscription: "Військкомат",
  health: "Стан здоров'я",
  healthComplaints: "Скарги на здоров'я",
  moralState: "Моральний стан",
  bloodType: "Група крові",
  shoeSize: "Розмір взуття",
  arrivalDate: "Дата прибуття",
  trainingPeriod: "Період навчання",
  specialization: "Спеціалізація",
  brand: "Марка",
  model: "Модель",
  licensePlate: "Держномер",
  year: "Рік випуску",
  vin: "VIN-код",
  fuelType: "Тип пального",
  tankCapacity: "Об'єм баку",
  liters: "Літри",
  pricePerLiter: "Ціна за літр",
  totalCost: "Загальна вартість",
  mileage: "Пробіг",
  driverName: "Водій",
  invoiceNumber: "Номер накладної",
  supplier: "Постачальник",
  purpose: "Призначення",
};
