export const COLUMN_ALIASES: Record<string, string> = {
  "піб": "fullName",
  "прізвище ім'я по батькові": "fullName",
  "прізвище ім'я по-батькові": "fullName",
  "звання": "rank",
  "військове звання": "rank",
  "дата народження": "birthDate",
  "день народження": "birthDate",
  "дата нар.": "birthDate",
  "місце народження": "birthPlace",
  "народ.": "birthPlace",
  "фото": "photo",
  "паспорт": "passport",
  "серія та номер паспорту": "passport",
  "паспорт видано": "passportIssued",
  "ким і коли виданий паспорт": "passportIssued",
  "іпн": "tin",
  "рнокпп": "tin",
  "військовий квиток": "militaryId",
  "№ військового квитка": "militaryId",
  "в/к видано": "militaryIdIssued",
  "ким і коли виданий в/к": "militaryIdIssued",
  "убд": "ubd",
  "дата убд": "ubdDate",
  "в/ч": "serviceUnit",
  "військова частина": "serviceUnit",
  "роки служби": "serviceYears",
  "цивільна робота": "civilianJob",
  "фах": "civilianJob",
  "освіта": "education",
  "фактична адреса": "actualAddress",
  "адреса проживання": "actualAddress",
  "прописка": "registrationAddress",
  "адреса реєстрації": "registrationAddress",
  "водійське": "driverLicense",
  "посвідчення водія": "driverLicense",
  "судимість": "criminalRecord",
  "поліція": "policeRecords",
  "адмін-порушення": "policeRecords",
  "склад сім'ї": "family",
  "родина": "family",
  "телефон": "phone",
  "номер телефону": "phone",
  "тел.": "phone",
  "телефони рідних": "relativePhones",
  "родичі телефон": "relativePhones",
  "особисте розпорядження": "personalOrder",
  "призваний": "conscription",
  "ртцк": "conscription",
  "стан здоров'я": "health",
  "здоров'я": "health",
  "скарги": "healthComplaints",
  "моральний стан": "moralState",
  "морально-психологічний": "moralState",
  "група крові": "bloodType",
  "кров": "bloodType",
  "розмір взуття": "shoeSize",
  "взуття": "shoeSize",
  "примітки": "notes",
  "нотатки": "notes",
  "статус": "status",
  "дата прибуття": "arrivalDate",
  "прибуття": "arrivalDate",
  "період навчання": "trainingPeriod",
  "навчання": "trainingPeriod",
  "спеціалізація": "specialization",
  "спеціальність": "specialization",
};

export const STATUS_ALIASES: Record<string, string> = {
  "навчання": "training",
  "навчається": "training",
  "training": "training",
  "випущено": "graduated",
  "graduate": "graduated",
  "graduated": "graduated",
  "переведено": "transferred",
  "transferred": "transferred",
  "не склав": "failed",
  "failed": "failed",
};

export const ALLOWED_FIELDS = new Set([
  "fullName", "rank", "birthDate", "birthPlace", "photo",
  "passport", "passportIssued", "tin", "militaryId", "militaryIdIssued",
  "ubd", "ubdDate", "serviceUnit", "serviceYears", "civilianJob",
  "education", "actualAddress", "registrationAddress", "driverLicense",
  "criminalRecord", "policeRecords", "family", "phone", "relativePhones",
  "personalOrder", "conscription", "health", "healthComplaints",
  "moralState", "bloodType", "shoeSize", "notes", "status",
  "arrivalDate", "trainingPeriod", "specialization",
]);
