import type { BzvpPersonnel } from "./types";

export const BZVP_MOCK: BzvpPersonnel[] = [
  {
    id: "bzvp-001",
    rank: "старший солдат",
    fullName: "Ковальчук Андрій Петрович",
    birthDate: "12.04.2000",
    birthPlace: "м. Житомир",
    photo: undefined,
    passport: "АА 123456",
    passportIssued: "12.04.2016 Житомирським РУП",
    tin: "3000512345",
    militaryId: "МК 789012",
    militaryIdIssued: "15.06.2018 Житомірським ТЦК та СП",
    ubd: "Так",
    ubdDate: "01.03.2025",
    serviceUnit: "72 ОМБр",
    serviceYears: "2020-2024",
    civilianJob: "Електрик, ТОВ «Енергія»",
    education: "Житомирський політехнічний коледж, 2019, «Електроенергетика»",
    actualAddress: "м. Житомир, вул. Перемоги 15, кв. 42",
    registrationAddress: "м. Житомир, вул. Перемоги 15, кв. 42",
    driverLicense: "Категорія B, C",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Мати: Ковальчук О.В., 1975 р.н., м. Житомир, вул. Перемоги 15, кв. 42",
    phone: "+380 50 111 22 33",
    relativePhones: "Мати: +380 67 111 22 33",
    personalOrder: "Без розпоряджень",
    conscription: "Житомирським РТЦК та СП",
    health: "Задовільний. Хронічних захворювань немає",
    healthComplaints: "Скарг немає",
    moralState: "Стабільний. Стресостійкий",
    bloodType: "A(II) Rh+",
    shoeSize: "43",
    notes: "Рекомендований до командирської посади",
    status: "training",
    arrivalDate: "01.06.2026",
    trainingPeriod: "2 міс.",
    specialization: "Стрілець",
  },
  {
    id: "bzvp-002",
    rank: "молодший сержант",
    fullName: "Шевченко Олег Миколайович",
    birthDate: "25.08.1999",
    birthPlace: "м. Дніпро",
    photo: undefined,
    passport: "АБ 654321",
    passportIssued: "25.08.2015 Дніпровським РУП №1",
    tin: "2998812345",
    militaryId: "МК 456789",
    militaryIdIssued: "10.09.2017 Дніпровським ТЦК та СП",
    ubd: "Так",
    ubdDate: "15.06.2024",
    serviceUnit: "93 ОМБр",
    serviceYears: "2019-2025",
    civilianJob: "Зварювальник, ПАТ «Дніпросталь»",
    education: "Дніпровський індустріальний коледж, 2018, «Зварювальне виробництво»",
    actualAddress: "м. Дніпро, пр. Слобожанський 45, кв. 12",
    registrationAddress: "м. Дніпро, пр. Слобожанський 45, кв. 12",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Дружина: Шевченко А.В., 2000 р.н.; Син: Шевченко Д.О., 2022 р.н. — м. Дніпро, пр. Слобожанський 45, кв. 12",
    phone: "+380 67 444 55 66",
    relativePhones: "Дружина: +380 50 444 55 66",
    personalOrder: "Без розпоряджень",
    conscription: "Дніпровським РТЦК та СП",
    health: "Задовільний. Легка форма алергії (квітковий пилок)",
    healthComplaints: "Періодичний головний біль",
    moralState: "Задовільний",
    bloodType: "0(I) Rh-",
    shoeSize: "44",
    notes: "",
    status: "training",
    arrivalDate: "15.05.2026",
    trainingPeriod: "1 міс.",
    specialization: "Гранатометник",
  },
  {
    id: "bzvp-003",
    rank: "сержант",
    fullName: "Бондаренко Дмитро Іванович",
    birthDate: "03.11.2001",
    birthPlace: "м. Черкаси",
    photo: undefined,
    passport: "АВ 987654",
    passportIssued: "03.11.2017 Черкаським РУП",
    tin: "3123498765",
    militaryId: "МК 345678",
    militaryIdIssued: "20.12.2019 Черкаським ТЦК та СП",
    ubd: "Так",
    ubdDate: "10.08.2024",
    serviceUnit: "10 ОГШБр",
    serviceYears: "2020-2025",
    civilianJob: "Водій, ТОВ «Логістик»",
    education: "Черкаський професійний ліцей, 2019, «Водій автотранспортних засобів»",
    actualAddress: "м. Черкаси, вул. Хрещатик 28, кв. 5",
    registrationAddress: "м. Черкаси, вул. Хрещатик 28, кв. 5",
    driverLicense: "Категорія B, C, D",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Мати: Бондаренко Н.В., 1978 р.н.; Батько: Бондаренко І.О., 1976 р.н. — м. Черкаси, вул. Хрещатик 28, кв. 5",
    phone: "+380 63 222 33 44",
    relativePhones: "Мати: +380 67 222 33 44",
    personalOrder: "Заборона виїзду за межі області",
    conscription: "Черкаським РТЦК та СП",
    health: "Практично здоровий",
    healthComplaints: "Скарг немає",
    moralState: "Високий. Відповідальний, дисциплінований",
    bloodType: "B(III) Rh+",
    shoeSize: "42",
    notes: "Рекомендований до сержантської посади",
    status: "graduated",
    arrivalDate: "20.04.2026",
    trainingPeriod: "1.5 міс.",
    specialization: "Кулеметник",
  },
  {
    id: "bzvp-004",
    rank: "капітан",
    fullName: "Мельник Сергій Васильович",
    birthDate: "18.02.1998",
    birthPlace: "м. Львів",
    photo: "/avatars/avatar-4.jpg",
    passport: "АГ 456789",
    passportIssued: "18.02.2014 Львівським РУП №2",
    tin: "2987612345",
    militaryId: "МК 234567",
    militaryIdIssued: "01.07.2016 Львівським ТЦК та СП",
    ubd: "Так",
    ubdDate: "20.03.2023",
    serviceUnit: "56 ОМПБр",
    serviceYears: "2017-2025",
    civilianJob: "Менеджер, ТОВ «Галич-Трейд»",
    education: "Львівський національний університет ім. Франка, 2020, «Правознавство»",
    actualAddress: "м. Львів, вул. Стрийська 120, кв. 34",
    registrationAddress: "м. Львів, вул. Стрийська 120, кв. 34",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Дружина: Мельник І.Р., 1999 р.н.; Донька: Мельник С.С., 2021 р.н. — м. Львів, вул. Стрийська 120, кв. 34",
    phone: "+380 95 777 88 99",
    relativePhones: "Дружина: +380 50 777 88 99",
    personalOrder: "Без розпоряджень",
    conscription: "Львівським обласним ТЦК та СП",
    health: "Задовільний. Захворювань немає",
    healthComplaints: "Скарг немає",
    moralState: "Високий. Лідерські якості",
    bloodType: "AB(IV) Rh+",
    shoeSize: "43",
    notes: "Переведений до 93 ОМБр",
    status: "transferred",
    arrivalDate: "10.03.2026",
    trainingPeriod: "2 міс.",
    specialization: "Снайпер",
  },
  {
    id: "bzvp-005",
    rank: "солдат",
    fullName: "Ткаченко Роман Олександрович",
    birthDate: "30.06.2002",
    birthPlace: "м. Полтава",
    photo: undefined,
    passport: "АД 321654",
    passportIssued: "30.06.2018 Полтавським РУП",
    tin: "3221098765",
    militaryId: "МК 567890",
    militaryIdIssued: "12.11.2020 Полтавським ТЦК та СП",
    ubd: "Ні",
    ubdDate: undefined,
    serviceUnit: "53 ОМБр",
    serviceYears: "2021-2025",
    civilianJob: "Продавець, магазин «Електроніка»",
    education: "Полтавський коледж економіки, 2021, «Товарознавство»",
    actualAddress: "м. Полтава, вул. Європейська 8, кв. 15",
    registrationAddress: "м. Полтава, вул. Європейська 8, кв. 15",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Батьки: Ткаченко О.І., 1975 р.н., Ткаченко Л.В., 1978 р.н. — м. Полтава, вул. Європейська 8, кв. 15",
    phone: "+380 99 333 44 55",
    relativePhones: "Батько: +380 67 333 44 55",
    personalOrder: "Відстрочка від бойових виїздів до завершення навчання",
    conscription: "Полтавським РТЦК та СП",
    health: "Задовільний. Короткозорість -1.5",
    healthComplaints: "Скарг немає",
    moralState: "Задовільний. Потребує адаптації",
    bloodType: "A(II) Rh-",
    shoeSize: "44",
    notes: "",
    status: "training",
    arrivalDate: "05.06.2026",
    trainingPeriod: "1 міс.",
    specialization: undefined,
  },
  {
    id: "bzvp-006",
    rank: "старший солдат",
    fullName: "Кравченко Ігор Анатолійович",
    birthDate: "14.09.1997",
    birthPlace: "м. Харків",
    photo: undefined,
    passport: "АЕ 789123",
    passportIssued: "14.09.2013 Харківським РУП №3",
    tin: "2884512345",
    militaryId: "МК 890123",
    militaryIdIssued: "05.05.2015 Харківським ТЦК та СП",
    ubd: "Так",
    ubdDate: "01.02.2024",
    serviceUnit: "128 ОГШБр",
    serviceYears: "2016-2025",
    civilianJob: "Інженер зв'язку, ПАТ «Укртелеком»",
    education: "Харківський національний університет радіоелектроніки, 2019, «Телекомунікації»",
    actualAddress: "м. Харків, вул. Сумська 56, кв. 8",
    registrationAddress: "м. Харків, вул. Сумська 56, кв. 8",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Дружина: Кравченко О.С., 1998 р.н. — м. Харків, вул. Сумська 56, кв. 8",
    phone: "+380 63 555 66 77",
    relativePhones: "Дружина: +380 50 555 66 77",
    personalOrder: "Без розпоряджень",
    conscription: "Харківським обласним ТЦК та СП",
    health: "Задовільний. Хронічних захворювань немає",
    healthComplaints: "Періодичний біль у спині після навантажень",
    moralState: "Стабільний. Витривалий",
    bloodType: "0(I) Rh+",
    shoeSize: "42",
    notes: "",
    status: "training",
    arrivalDate: "22.05.2026",
    trainingPeriod: "2 міс.",
    specialization: "Радіотелефоніст",
  },
  {
    id: "bzvp-007",
    rank: "солдат",
    fullName: "Олійник Віталій Володимирович",
    birthDate: "07.12.2000",
    birthPlace: "м. Вінниця",
    photo: undefined,
    passport: "АЖ 456321",
    passportIssued: "07.12.2016 Вінницьким РУП",
    tin: "3124589632",
    militaryId: "МК 678901",
    militaryIdIssued: "18.03.2018 Вінницьким ТЦК та СП",
    ubd: "Ні",
    ubdDate: undefined,
    serviceUnit: "30 ОМБр",
    serviceYears: "2019-2024",
    civilianJob: "Будівельник, ТОВ «Буд-Майстер»",
    education: "Вінницький будівельний коледж, 2019, «Будівництво та експлуатація будівель»",
    actualAddress: "м. Вінниця, вул. Космонавтів 12, кв. 3",
    registrationAddress: "м. Вінниця, вул. Космонавтів 12, кв. 3",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Адмін-порушення: 2023 р. — дрібне хуліганство (закрито)",
    family: "Мати: Олійник В.С., 1976 р.н. — м. Вінниця, вул. Космонавтів 12, кв. 3",
    phone: "+380 97 888 99 00",
    relativePhones: "Мати: +380 63 888 99 00",
    personalOrder: "Без розпоряджень",
    conscription: "Вінницьким РТЦК та СП",
    health: "Задовільний. Має алергію на антибіотики",
    healthComplaints: "Скарги на зниження слуху (контузія 2023)",
    moralState: "Нестабільний. Потребує психологічної підтримки",
    bloodType: "A(II) Rh+",
    shoeSize: "45",
    notes: "Не склав норматив з вогневої підготовки. Потребує повторного курсу",
    status: "failed",
    arrivalDate: "01.04.2026",
    trainingPeriod: "1.5 міс.",
    specialization: "Стрілець",
  },
  {
    id: "bzvp-008",
    rank: "молодший лейтенант",
    fullName: "Савченко Павло Юрійович",
    birthDate: "21.03.2003",
    birthPlace: "м. Одеса",
    photo: undefined,
    passport: "АЗ 654987",
    passportIssued: "21.03.2019 Одеським РУП №2",
    tin: "3300123456",
    militaryId: "МК 123789",
    militaryIdIssued: "01.09.2021 Одеським ТЦК та СП",
    ubd: "Ні",
    ubdDate: undefined,
    serviceUnit: "95 ОДШБр",
    serviceYears: "2022-2025",
    civilianJob: "Студент",
    education: "Одеська військова академія, 2025 (заочно), «Управління діями підрозділів»",
    actualAddress: "м. Одеса, вул. Дерибасівська 20, кв. 5",
    registrationAddress: "м. Одеса, вул. Дерибасівська 20, кв. 5",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Батьки: Савченко Ю.О., 1978 р.н., Савченко І.М., 1980 р.н. — м. Одеса, вул. Дерибасівська 20, кв. 5",
    phone: "+380 99 777 88 99",
    relativePhones: "Батько: +380 67 777 88 99",
    personalOrder: "Без розпоряджень",
    conscription: "Одеським РТЦК та СП",
    health: "Задовільний. Протипоказань немає",
    healthComplaints: "Скарг немає",
    moralState: "Високий. Мотивований",
    bloodType: "B(III) Rh+",
    shoeSize: "43",
    notes: "",
    status: "training",
    arrivalDate: "12.06.2026",
    trainingPeriod: "1 міс.",
    specialization: undefined,
  },
  {
    id: "bzvp-009",
    rank: "старший сержант",
    fullName: "Гриценко Максим Богданович",
    birthDate: "05.07.1996",
    birthPlace: "м. Рівне",
    photo: undefined,
    passport: "АИ 789456",
    passportIssued: "05.07.2012 Рівненським РУП",
    tin: "2785412369",
    militaryId: "МК 456123",
    militaryIdIssued: "10.10.2014 Рівненським ТЦК та СП",
    ubd: "Так",
    ubdDate: "12.09.2023",
    serviceUnit: "14 ОМБр",
    serviceYears: "2015-2025",
    civilianJob: "Поліцейський, ГУНП у Рівненській області",
    education: "Рівненський державний гуманітарний університет, 2017, «Правознавство»",
    actualAddress: "м. Рівне, вул. Соборна 45, кв. 10",
    registrationAddress: "м. Рівне, вул. Соборна 45, кв. 10",
    driverLicense: "Категорія B, C",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Дружина: Гриценко Т.М., 1997 р.н.; Син: Гриценко М.М., 2020 р.н.; Донька: Гриценко А.М., 2022 р.н. — м. Рівне, вул. Соборна 45, кв. 10",
    phone: "+380 67 111 22 33",
    relativePhones: "Дружина: +380 50 111 22 33",
    personalOrder: "Без розпоряджень",
    conscription: "Рівненським РТЦК та СП",
    health: "Задовільний. Захворювань немає",
    healthComplaints: "Періодичний біль у коліні (травма 2023)",
    moralState: "Високий. Досвідчений, врівноважений",
    bloodType: "A(II) Rh+",
    shoeSize: "43",
    notes: "Рекомендований до командирської посади. Досвід участі в бойових діях",
    status: "graduated",
    arrivalDate: "18.05.2026",
    trainingPeriod: "2 міс.",
    specialization: "Командир відділення",
  },
  {
    id: "bzvp-010",
    rank: "лейтенант",
    fullName: "Лисенко Артем Вікторович",
    birthDate: "28.10.2001",
    birthPlace: "м. Запоріжжя",
    photo: undefined,
    passport: "АК 321987",
    passportIssued: "28.10.2017 Запорізьким РУП",
    tin: "3225478963",
    militaryId: "МК 789654",
    militaryIdIssued: "15.01.2020 Запорізьким ТЦК та СП",
    ubd: "Так",
    ubdDate: "05.04.2024",
    serviceUnit: "24 ОМБр",
    serviceYears: "2020-2025",
    civilianJob: "Охоронець, ТОВ «Титан-Сек'юріті»",
    education: "Запорізький національний університет, 2023, «Фізичне виховання та спорт»",
    actualAddress: "м. Запоріжжя, пр. Металургів 30, кв. 18",
    registrationAddress: "м. Запоріжжя, пр. Металургів 30, кв. 18",
    driverLicense: "Категорія B",
    criminalRecord: "Немає",
    policeRecords: "Немає",
    family: "Мати: Лисенко В.П., 1978 р.н.; Сестра: Лисенко О.В., 2005 р.н. — м. Запоріжжя, пр. Металургів 30, кв. 18",
    phone: "+380 63 222 33 44",
    relativePhones: "Мати: +380 95 222 33 44",
    personalOrder: "Без розпоряджень",
    conscription: "Запорізьким РТЦК та СП",
    health: "Задовільний. Хронічних захворювань немає",
    healthComplaints: "Скарг немає",
    moralState: "Стабільний. Дисциплінований",
    bloodType: "0(I) Rh+",
    shoeSize: "44",
    notes: "",
    status: "transferred",
    arrivalDate: "25.04.2026",
    trainingPeriod: "1.5 міс.",
    specialization: "Розвідник",
  },
];
