import type { MilitaryPersonnel } from "./types";

export const MOCK_TOTAL_DB_COUNT = 124;

export const MOCK_PERSONNEL = [
  {
    fullName: "Іванов Іван Іванович",
    rank: "старший лейтенант",
    position: "Командир взводу",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "1998-03-15",
    experience: 6,
    missions: 24,
    phone: "+380 67 123 45 67",
    lastActiveDays: 2,
    achievements: [
      {
        name: "Відзнака «За зразкову службу»",
        date: "--",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АКС-74У",
        type: "weapon",
        serialNumber: "АКС-334455",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-11223",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "176 см",
      chest: "92 см",
      waist: "78 см",
      shoes: "42",
      headgear: "57",
      uniform: "46/2",
    },
    positionHistory: [
      {
        position: "Командир взводу",
        unit: "2-га механізована бригада",
        startDate: "06.2023",
      },
      {
        position: "Командир відділення",
        unit: "2-га механізована бригада",
        startDate: "03.2021",
        endDate: "06.2023",
      },
      {
        position: "Стрілець-санітар",
        unit: "2-га механізована бригада",
        startDate: "09.2019",
        endDate: "03.2021",
      },
    ],
  },
  {
    fullName: "Петренко Сергій Олександрович",
    rank: "капітан",
    position: "Заступник командира роти",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "1995-07-22",
    experience: 8,
    missions: 31,
    phone: "+380 50 987 65 43",
    email: "s.petrenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Орден «За мужність» II ступеня",
        date: "--",
        type: "medal",
      },
      {
        name: "Подяка командира батальйону",
        date: "--",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-556677",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-66778",
        issuedDate: "--",
      },
      {
        name: "Радіостанція Motorola",
        type: "gear",
        serialNumber: "МТ-8899",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "182 см",
      chest: "98 см",
      waist: "84 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Заступник командира роти",
        unit: "3-тя штурмова бригада",
        startDate: "01.2024",
      },
      {
        position: "Командир взводу",
        unit: "3-тя штурмова бригада",
        startDate: "03.2021",
        endDate: "01.2024",
      },
      {
        position: "Командир відділення",
        unit: "3-тя штурмова бригада",
        startDate: "05.2019",
        endDate: "03.2021",
      },
    ],
  },
  {
    fullName: "Коваленко Дмитро Вікторович",
    rank: "сержант",
    position: "Старший оператор БПЛА",
    unit: "Окрема бригада дронів",
    status: "active",
    birthDate: "2000-11-10",
    experience: 4,
    missions: 18,
    phone: "+380 95 555 44 33",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Сертифікат оператора БПЛА класу «Mavic»",
        date: "--",
        type: "certificate",
      },
    ],
    equipment: [
      {
        name: "Mavic 3E (БПЛА)",
        type: "gear",
        serialNumber: "M3E-778899",
        issuedDate: "--",
      },
      {
        name: "Пістолет ПМ",
        type: "weapon",
        serialNumber: "ПМ-445566",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "174 см",
      chest: "90 см",
      waist: "76 см",
      shoes: "41",
      headgear: "56",
      uniform: "44/2",
    },
    positionHistory: [
      {
        position: "Старший оператор БПЛА",
        unit: "Окрема бригада дронів",
        startDate: "09.2023",
      },
      {
        position: "Оператор БПЛА",
        unit: "Окрема бригада дронів",
        startDate: "03.2022",
        endDate: "09.2023",
      },
    ],
  },
  {
    fullName: "Сидоренко Олександр Павлович",
    rank: "майор",
    position: "Начальник штабу батальйону",
    unit: "1-ша танкова бригада",
    status: "wounded",
    birthDate: "1992-05-05",
    experience: 10,
    missions: 45,
    phone: "+380 44 333 22 11",
    email: "o.sydorenko@mil.gov.ua",
    lastActiveDays: 1,
    medicalRecords: [
      {
        condition: "Мінно-вибухова травма",
        diagnosisDate: "--",
        status: "active",
      },
      {
        condition: "Контузія головного мозку",
        diagnosisDate: "--",
        status: "active",
      },
    ],
    achievements: [
      {
        name: "Орден Богдана Хмельницького III ступеня",
        date: "--",
        type: "medal",
      },
    ],
    equipment: [
      {
        name: "Пістолет Макарова ПМ",
        type: "weapon",
        serialNumber: "ПМ-987654",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-54321",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "178 см",
      chest: "100 см",
      waist: "86 см",
      shoes: "42",
    },
  },
  {
    fullName: "Мельник Андрій Васильович",
    rank: "лейтенант",
    position: "Командир відділення",
    unit: "1-ша танкова бригада",
    status: "vacation",
    birthDate: "1999-08-12",
    experience: 3,
    missions: 8,
    phone: "+380 63 777 88 99",
    lastActiveDays: 18,
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-998877",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-33456",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "170 см",
      chest: "88 см",
      waist: "74 см",
      shoes: "40",
      headgear: "55",
      uniform: "44/1",
    },
    positionHistory: [
      {
        position: "Командир відділення",
        unit: "1-ша танкова бригада",
        startDate: "11.2023",
      },
      {
        position: "Стрілець-санітар",
        unit: "1-ша танкова бригада",
        startDate: "05.2022",
        endDate: "11.2023",
      },
    ],
  },
  {
    fullName: "Ткаченко Олег Миколайович",
    rank: "капітан",
    position: "Командир роти",
    unit: "2-га механізована бригада",
    status: "reserve",
    birthDate: "1990-02-14",
    experience: 12,
    missions: 52,
    phone: "+380 66 222 33 44",
    email: "o.tkachenko@mil.gov.ua",
    lastActiveDays: 45,
    medicalRecords: [
      {
        condition: "Поранення лівої руки",
        diagnosisDate: "--",
        status: "resolved",
      },
      {
        condition: "Контузія",
        diagnosisDate: "--",
        status: "resolved",
      },
    ],
    achievements: [
      {
        name: "Орден «За мужність» III ступеня",
        date: "--",
        type: "medal",
      },
      {
        name: "Відзнака «За врятоване життя»",
        date: "--",
        type: "medal",
      },
      {
        name: "Подяка командира бригади",
        date: "--",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-456789",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-12345",
        issuedDate: "--",
      },
      {
        name: "Каска MICH",
        type: "gear",
        serialNumber: "К-67890",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "180 см",
      chest: "96 см",
      waist: "82 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Командир роти",
        unit: "2-га механізована бригада",
        startDate: "01.2023",
      },
      {
        position: "Заступник командира роти",
        unit: "2-га механізована бригада",
        startDate: "03.2021",
        endDate: "01.2023",
      },
      {
        position: "Командир взводу",
        unit: "2-га механізована бригада",
        startDate: "06.2018",
        endDate: "03.2021",
      },
    ],
  },
  {
    fullName: "Бондаренко Сергій Петрович",
    rank: "сержант",
    position: "Стрілець-санітар",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "1997-06-03",
    experience: 5,
    missions: 14,
    phone: "+380 97 111 22 33",
    lastActiveDays: 0,
    medicalRecords: [
      {
        condition: "Забій грудної клітки",
        diagnosisDate: "--",
        status: "resolved",
      },
    ],
    equipment: [
      {
        name: "Автомат АКС-74",
        type: "weapon",
        serialNumber: "АКС-223344",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-77889",
        issuedDate: "--",
      },
      {
        name: "Аптечка тактична IFAK",
        type: "gear",
        serialNumber: "ІФ-1122",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "179 см",
      chest: "94 см",
      waist: "80 см",
      shoes: "42",
      headgear: "57",
      uniform: "46/2",
    },
    positionHistory: [
      {
        position: "Стрілець-санітар",
        unit: "3-тя штурмова бригада",
        startDate: "03.2023",
      },
      {
        position: "Стрілець",
        unit: "3-тя штурмова бригада",
        startDate: "08.2021",
        endDate: "03.2023",
      },
    ],
  },
  {
    fullName: "Романенко Віктор Ігорович",
    rank: "полковник",
    position: "Командир бригади",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "1985-11-20",
    experience: 17,
    missions: 68,
    email: "v.romanenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Герой України — орден «Золота Зірка»",
        date: "--",
        type: "medal",
      },
      {
        name: "Орден Богдана Хмельницького II ступеня",
        date: "--",
        type: "medal",
      },
      {
        name: "Орден «За мужність» I ступеня",
        date: "--",
        type: "medal",
      },
      {
        name: "Відзнака Президента «За оборону України»",
        date: "--",
        type: "certificate",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74М",
        type: "weapon",
        serialNumber: "АК-112233",
        issuedDate: "--",
      },
      {
        name: "Пістолет Glock 17",
        type: "weapon",
        serialNumber: "GL-445566",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-99887",
        issuedDate: "--",
      },
      {
        name: "Шолом Kevlar ACH",
        type: "gear",
        serialNumber: "Ш-55667",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "185 см",
      chest: "104 см",
      waist: "90 см",
      shoes: "44",
      headgear: "59",
      uniform: "50/4",
    },
    positionHistory: [
      {
        position: "Командир бригади",
        unit: "2-га механізована бригада",
        startDate: "01.2023",
      },
      {
        position: "Заступник командира бригади",
        unit: "2-га механізована бригада",
        startDate: "06.2020",
        endDate: "01.2023",
      },
      {
        position: "Командир батальйону",
        unit: "2-га механізована бригада",
        startDate: "01.2016",
        endDate: "06.2020",
      },
      {
        position: "Командир роти",
        unit: "2-га механізована бригада",
        startDate: "08.2012",
        endDate: "01.2016",
      },
    ],
  },
  {
    fullName: "Гриценко Павло Олегович",
    rank: "лейтенант",
    position: "Офіцер розвідки",
    unit: "Окрема бригада дронів",
    status: "wounded",
    birthDate: "2001-04-08",
    experience: 2,
    missions: 6,
    phone: "+380 73 444 55 66",
    lastActiveDays: 2,
    medicalRecords: [
      {
        condition: "Осколкове поранення плеча",
        diagnosisDate: "--",
        status: "active",
      },
    ],
    equipment: [
      {
        name: "Прилад нічного бачення",
        type: "gear",
        serialNumber: "ПНБ-3344",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-22345",
        issuedDate: "--",
      },
    ],
    positionHistory: [
      {
        position: "Офіцер розвідки",
        unit: "Окрема бригада дронів",
        startDate: "01.2025",
      },
      {
        position: "Розвідник-кулеметник",
        unit: "Окрема бригада дронів",
        startDate: "06.2023",
        endDate: "01.2025",
      },
    ],
  },
  {
    fullName: "Шевченко Тарас Григорович",
    rank: "майор",
    position: "Начальник розвідки",
    unit: "3-тя штурмова бригада",
    status: "active",
    birthDate: "1988-09-17",
    experience: 14,
    missions: 56,
    phone: "+380 50 888 99 00",
    email: "t.shevchenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Орден «За мужність» II ступеня",
        date: "--",
        type: "medal",
      },
      {
        name: "Медаль «За військову службу Україні»",
        date: "--",
        type: "medal",
      },
      {
        name: "Подяка Головнокомандувача ЗСУ",
        date: "--",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74М",
        type: "weapon",
        serialNumber: "АК-665544",
        issuedDate: "--",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-55667",
        issuedDate: "--",
      },
      {
        name: "Бінокль тактичний",
        type: "gear",
        serialNumber: "БН-2233",
        issuedDate: "--",
      },
    ],
    clothingSizes: {
      height: "183 см",
      chest: "100 см",
      waist: "86 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Начальник розвідки",
        unit: "3-тя штурмова бригада",
        startDate: "01.2024",
      },
      {
        position: "Заступник начальника розвідки",
        unit: "3-тя штурмова бригада",
        startDate: "03.2021",
        endDate: "01.2024",
      },
      {
        position: "Старший розвідник",
        unit: "3-тя штурмова бригада",
        startDate: "04.2018",
        endDate: "03.2021",
      },
      {
        position: "Розвідник",
        unit: "3-тя штурмова бригада",
        startDate: "09.2014",
        endDate: "04.2018",
      },
    ],
  },
] as MilitaryPersonnel[];
