import type { MilitaryPersonnel } from "./types";

export const MOCK_TOTAL_DB_COUNT = 124;

export const MOCK_PERSONNEL: MilitaryPersonnel[] = [
  {
    id: "1",
    fullName: "Іванов Іван Іванович",
    rank: "старший лейтенант",
    position: "Командир взводу",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "15.03.1998",
    experience: 6,
    missions: 24,
    phone: "+380 67 123 45 67",
    lastActive: "2 години тому",
  },
  {
    id: "2",
    fullName: "Петренко Сергій Олександрович",
    rank: "капітан",
    position: "Заступник командира роти",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "22.07.1995",
    experience: 8,
    missions: 31,
    phone: "+380 50 987 65 43",
    email: "s.petrenko@mil.gov.ua",
    lastActive: "5 годин тому",
  },
  {
    id: "3",
    fullName: "Коваленко Дмитро Вікторович",
    rank: "сержант",
    position: "Старший оператор БПЛА",
    unit: "Окрема бригада дронів",
    status: "active",
    birthDate: "10.11.2000",
    experience: 4,
    missions: 18,
    phone: "+380 95 555 44 33",
    lastActive: "1 годину тому",
  },
  {
    id: "4",
    fullName: "Сидоренко Олександр Павлович",
    rank: "майор",
    position: "Начальник штабу батальйону",
    unit: "1-ша танкова бригада",
    status: "wounded",
    birthDate: "05.05.1992",
    experience: 10,
    missions: 45,
    phone: "+380 44 333 22 11",
    email: "o.sydorenko@mil.gov.ua",
    lastActive: "вчора",
  },
  {
    id: "5",
    fullName: "Мельник Андрій Васильович",
    rank: "лейтенант",
    position: "Командир відділення",
    unit: "1-ша танкова бригада",
    status: "vacation",
    birthDate: "12.08.1999",
    experience: 3,
    missions: 8,
    phone: "+380 63 777 88 99",
    lastActive: "3 дні тому",
  },
  {
    id: "6",
    fullName: "Ткаченко Олег Миколайович",
    rank: "капітан",
    position: "Командир роти",
    unit: "2-га механізована бригада",
    status: "reserve",
    birthDate: "14.02.1990",
    experience: 12,
    missions: 52,
    phone: "+380 66 222 33 44",
    email: "o.tkachenko@mil.gov.ua",
    lastActive: "тиждень тому",
  },
  {
    id: "7",
    fullName: "Бондаренко Сергій Петрович",
    rank: "сержант",
    position: "Стрілець-санітар",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "03.06.1997",
    experience: 5,
    missions: 14,
    phone: "+380 97 111 22 33",
    lastActive: "30 хвилин тому",
  },
  {
    id: "8",
    fullName: "Романенко Віктор Ігорович",
    rank: "полковник",
    position: "Командир бригади",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "20.11.1985",
    experience: 17,
    missions: 68,
    email: "v.romanenko@mil.gov.ua",
    lastActive: "1 годину тому",
  },
  {
    id: "9",
    fullName: "Гриценко Павло Олегович",
    rank: "лейтенант",
    position: "Офіцер розвідки",
    unit: "Окрема бригада дронів",
    status: "wounded",
    birthDate: "08.04.2001",
    experience: 2,
    missions: 6,
    phone: "+380 73 444 55 66",
    lastActive: "2 дні тому",
  },
  {
    id: "10",
    fullName: "Шевченко Тарас Григорович",
    rank: "майор",
    position: "Начальник розвідки",
    unit: "3-тя штурмова бригада",
    status: "active",
    birthDate: "17.09.1988",
    experience: 14,
    missions: 56,
    phone: "+380 50 888 99 00",
    email: "t.shevchenko@mil.gov.ua",
    lastActive: "15 хвилин тому",
  },
];
