import type { MilitaryPersonnel } from "./types";

export const MOCK_TOTAL_DB_COUNT = 124;

export const MOCK_PERSONNEL: MilitaryPersonnel[] = [
  {
    id: "1",
    fullName: "Іванов Іван Іванович",
    rank: "старший лейтенант",
    position: "Командир взводу",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "15.03.1998",
    experience: 6,
    missions: 24,
    phone: "+380 67 123 45 67",
    lastActiveDays: 2,
    achievements: [
      {
        name: "Відзнака «За зразкову службу»",
        date: "06.12.2024",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АКС-74У",
        type: "weapon",
        serialNumber: "АКС-334455",
        issuedDate: "10.06.2023",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-11223",
        issuedDate: "10.06.2023",
      },
    ],
    clothingSizes: {
      height: "176 см",
      chest: "92 см",
      waist: "78 см",
      shoes: "42",
      headgear: "57",
      uniform: "46/2",
    },
    positionHistory: [
      {
        position: "Командир взводу",
        unit: "2-га механізована бригада",
        startDate: "06.2023",
      },
      {
        position: "Командир відділення",
        unit: "2-га механізована бригада",
        startDate: "03.2021",
        endDate: "06.2023",
      },
      {
        position: "Стрілець-санітар",
        unit: "2-га механізована бригада",
        startDate: "09.2019",
        endDate: "03.2021",
      },
    ],
  },
  {
    id: "2",
    fullName: "Петренко Сергій Олександрович",
    rank: "капітан",
    position: "Заступник командира роти",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "22.07.1995",
    experience: 8,
    missions: 31,
    phone: "+380 50 987 65 43",
    email: "s.petrenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Орден «За мужність» II ступеня",
        date: "14.10.2024",
        type: "medal",
      },
      {
        name: "Подяка командира батальйону",
        date: "20.02.2025",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-556677",
        issuedDate: "15.01.2022",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-66778",
        issuedDate: "15.01.2022",
      },
      {
        name: "Радіостанція Motorola",
        type: "gear",
        serialNumber: "МТ-8899",
        issuedDate: "01.03.2023",
      },
    ],
    clothingSizes: {
      height: "182 см",
      chest: "98 см",
      waist: "84 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Заступник командира роти",
        unit: "3-тя штурмова бригада",
        startDate: "01.2024",
      },
      {
        position: "Командир взводу",
        unit: "3-тя штурмова бригада",
        startDate: "03.2021",
        endDate: "01.2024",
      },
      {
        position: "Командир відділення",
        unit: "3-тя штурмова бригада",
        startDate: "05.2019",
        endDate: "03.2021",
      },
    ],
  },
  {
    id: "3",
    fullName: "Коваленко Дмитро Вікторович",
    rank: "сержант",
    position: "Старший оператор БПЛА",
    unit: "Окрема бригада дронів",
    status: "active",
    birthDate: "10.11.2000",
    experience: 4,
    missions: 18,
    phone: "+380 95 555 44 33",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Сертифікат оператора БПЛА класу «Mavic»",
        date: "15.05.2024",
        type: "certificate",
      },
    ],
    equipment: [
      {
        name: "Mavic 3E (БПЛА)",
        type: "gear",
        serialNumber: "M3E-778899",
        issuedDate: "20.06.2024",
      },
      {
        name: "Пістолет ПМ",
        type: "weapon",
        serialNumber: "ПМ-445566",
        issuedDate: "15.03.2023",
      },
    ],
    clothingSizes: {
      height: "174 см",
      chest: "90 см",
      waist: "76 см",
      shoes: "41",
      headgear: "56",
      uniform: "44/2",
    },
    positionHistory: [
      {
        position: "Старший оператор БПЛА",
        unit: "Окрема бригада дронів",
        startDate: "09.2023",
      },
      {
        position: "Оператор БПЛА",
        unit: "Окрема бригада дронів",
        startDate: "03.2022",
        endDate: "09.2023",
      },
    ],
  },
  {
    id: "4",
    fullName: "Сидоренко Олександр Павлович",
    rank: "майор",
    position: "Начальник штабу батальйону",
    unit: "1-ша танкова бригада",
    status: "wounded",
    birthDate: "05.05.1992",
    experience: 10,
    missions: 45,
    phone: "+380 44 333 22 11",
    email: "o.sydorenko@mil.gov.ua",
    lastActiveDays: 1,
    medicalRecords: [
      {
        condition: "Мінно-вибухова травма",
        diagnosisDate: "12.05.2025",
        status: "active",
      },
      {
        condition: "Контузія головного мозку",
        diagnosisDate: "12.05.2025",
        status: "active",
      },
    ],
    achievements: [
      {
        name: "Орден Богдана Хмельницького III ступеня",
        date: "24.08.2024",
        type: "medal",
      },
    ],
    equipment: [
      {
        name: "Пістолет Макарова ПМ",
        type: "weapon",
        serialNumber: "ПМ-987654",
        issuedDate: "15.03.2022",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-54321",
        issuedDate: "10.01.2023",
      },
    ],
    clothingSizes: {
      height: "178 см",
      chest: "100 см",
      waist: "86 см",
      shoes: "42",
    },
  },
  {
    id: "5",
    fullName: "Мельник Андрій Васильович",
    rank: "лейтенант",
    position: "Командир відділення",
    unit: "1-ша танкова бригада",
    status: "vacation",
    birthDate: "12.08.1999",
    experience: 3,
    missions: 8,
    phone: "+380 63 777 88 99",
    lastActiveDays: 18,
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-998877",
        issuedDate: "10.01.2024",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-33456",
        issuedDate: "10.01.2024",
      },
    ],
    clothingSizes: {
      height: "170 см",
      chest: "88 см",
      waist: "74 см",
      shoes: "40",
      headgear: "55",
      uniform: "44/1",
    },
    positionHistory: [
      {
        position: "Командир відділення",
        unit: "1-ша танкова бригада",
        startDate: "11.2023",
      },
      {
        position: "Стрілець-санітар",
        unit: "1-ша танкова бригада",
        startDate: "05.2022",
        endDate: "11.2023",
      },
    ],
  },
  {
    id: "6",
    fullName: "Ткаченко Олег Миколайович",
    rank: "капітан",
    position: "Командир роти",
    unit: "2-га механізована бригада",
    status: "reserve",
    birthDate: "14.02.1990",
    experience: 12,
    missions: 52,
    phone: "+380 66 222 33 44",
    email: "o.tkachenko@mil.gov.ua",
    lastActiveDays: 45,
    medicalRecords: [
      {
        condition: "Поранення лівої руки",
        diagnosisDate: "22.08.2024",
        status: "resolved",
      },
      {
        condition: "Контузія",
        diagnosisDate: "15.03.2024",
        status: "resolved",
      },
    ],
    achievements: [
      {
        name: "Орден «За мужність» III ступеня",
        date: "01.12.2023",
        type: "medal",
      },
      {
        name: "Відзнака «За врятоване життя»",
        date: "05.06.2024",
        type: "medal",
      },
      {
        name: "Подяка командира бригади",
        date: "10.03.2024",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74",
        type: "weapon",
        serialNumber: "АК-456789",
        issuedDate: "10.01.2023",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-12345",
        issuedDate: "10.01.2023",
      },
      {
        name: "Каска MICH",
        type: "gear",
        serialNumber: "К-67890",
        issuedDate: "10.01.2023",
      },
    ],
    clothingSizes: {
      height: "180 см",
      chest: "96 см",
      waist: "82 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Командир роти",
        unit: "2-га механізована бригада",
        startDate: "01.2023",
      },
      {
        position: "Заступник командира роти",
        unit: "2-га механізована бригада",
        startDate: "03.2021",
        endDate: "01.2023",
      },
      {
        position: "Командир взводу",
        unit: "2-га механізована бригада",
        startDate: "06.2018",
        endDate: "03.2021",
      },
    ],
  },
  {
    id: "7",
    fullName: "Бондаренко Сергій Петрович",
    rank: "сержант",
    position: "Стрілець-санітар",
    unit: "3-тя штурмова бригада",
    status: "on-mission",
    birthDate: "03.06.1997",
    experience: 5,
    missions: 14,
    phone: "+380 97 111 22 33",
    lastActiveDays: 0,
    medicalRecords: [
      {
        condition: "Забій грудної клітки",
        diagnosisDate: "02.04.2025",
        status: "resolved",
      },
    ],
    equipment: [
      {
        name: "Автомат АКС-74",
        type: "weapon",
        serialNumber: "АКС-223344",
        issuedDate: "01.08.2023",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-77889",
        issuedDate: "01.08.2023",
      },
      {
        name: "Аптечка тактична IFAK",
        type: "gear",
        serialNumber: "ІФ-1122",
        issuedDate: "01.08.2023",
      },
    ],
    clothingSizes: {
      height: "179 см",
      chest: "94 см",
      waist: "80 см",
      shoes: "42",
      headgear: "57",
      uniform: "46/2",
    },
    positionHistory: [
      {
        position: "Стрілець-санітар",
        unit: "3-тя штурмова бригада",
        startDate: "03.2023",
      },
      {
        position: "Стрілець",
        unit: "3-тя штурмова бригада",
        startDate: "08.2021",
        endDate: "03.2023",
      },
    ],
  },
  {
    id: "8",
    fullName: "Романенко Віктор Ігорович",
    rank: "полковник",
    position: "Командир бригади",
    unit: "2-га механізована бригада",
    status: "active",
    birthDate: "20.11.1985",
    experience: 17,
    missions: 68,
    email: "v.romanenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Герой України — орден «Золота Зірка»",
        date: "24.08.2024",
        type: "medal",
      },
      {
        name: "Орден Богдана Хмельницького II ступеня",
        date: "06.12.2023",
        type: "medal",
      },
      {
        name: "Орден «За мужність» I ступеня",
        date: "14.10.2022",
        type: "medal",
      },
      {
        name: "Відзнака Президента «За оборону України»",
        date: "01.12.2024",
        type: "certificate",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74М",
        type: "weapon",
        serialNumber: "АК-112233",
        issuedDate: "05.06.2022",
      },
      {
        name: "Пістолет Glock 17",
        type: "weapon",
        serialNumber: "GL-445566",
        issuedDate: "15.03.2023",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-99887",
        issuedDate: "05.06.2022",
      },
      {
        name: "Шолом Kevlar ACH",
        type: "gear",
        serialNumber: "Ш-55667",
        issuedDate: "05.06.2022",
      },
    ],
    clothingSizes: {
      height: "185 см",
      chest: "104 см",
      waist: "90 см",
      shoes: "44",
      headgear: "59",
      uniform: "50/4",
    },
    positionHistory: [
      {
        position: "Командир бригади",
        unit: "2-га механізована бригада",
        startDate: "01.2023",
      },
      {
        position: "Заступник командира бригади",
        unit: "2-га механізована бригада",
        startDate: "06.2020",
        endDate: "01.2023",
      },
      {
        position: "Командир батальйону",
        unit: "2-га механізована бригада",
        startDate: "01.2016",
        endDate: "06.2020",
      },
      {
        position: "Командир роти",
        unit: "2-га механізована бригада",
        startDate: "08.2012",
        endDate: "01.2016",
      },
    ],
  },
  {
    id: "9",
    fullName: "Гриценко Павло Олегович",
    rank: "лейтенант",
    position: "Офіцер розвідки",
    unit: "Окрема бригада дронів",
    status: "wounded",
    birthDate: "08.04.2001",
    experience: 2,
    missions: 6,
    phone: "+380 73 444 55 66",
    lastActiveDays: 2,
    medicalRecords: [
      {
        condition: "Осколкове поранення плеча",
        diagnosisDate: "18.03.2025",
        status: "active",
      },
    ],
    equipment: [
      {
        name: "Прилад нічного бачення",
        type: "gear",
        serialNumber: "ПНБ-3344",
        issuedDate: "01.02.2025",
      },
      {
        name: "Бронежилет «Корсар»",
        type: "armor",
        serialNumber: "БЖ-22345",
        issuedDate: "01.02.2025",
      },
    ],
    positionHistory: [
      {
        position: "Офіцер розвідки",
        unit: "Окрема бригада дронів",
        startDate: "01.2025",
      },
      {
        position: "Розвідник-кулеметник",
        unit: "Окрема бригада дронів",
        startDate: "06.2023",
        endDate: "01.2025",
      },
    ],
  },
  {
    id: "10",
    fullName: "Шевченко Тарас Григорович",
    rank: "майор",
    position: "Начальник розвідки",
    unit: "3-тя штурмова бригада",
    status: "active",
    birthDate: "17.09.1988",
    experience: 14,
    missions: 56,
    phone: "+380 50 888 99 00",
    email: "t.shevchenko@mil.gov.ua",
    lastActiveDays: 0,
    achievements: [
      {
        name: "Орден «За мужність» II ступеня",
        date: "14.10.2024",
        type: "medal",
      },
      {
        name: "Медаль «За військову службу Україні»",
        date: "06.12.2022",
        type: "medal",
      },
      {
        name: "Подяка Головнокомандувача ЗСУ",
        date: "01.12.2024",
        type: "commendation",
      },
    ],
    equipment: [
      {
        name: "Автомат АК-74М",
        type: "weapon",
        serialNumber: "АК-665544",
        issuedDate: "10.01.2021",
      },
      {
        name: "Бронежилет «Корсар-М3»",
        type: "armor",
        serialNumber: "БЖ-55667",
        issuedDate: "10.01.2021",
      },
      {
        name: "Бінокль тактичний",
        type: "gear",
        serialNumber: "БН-2233",
        issuedDate: "15.03.2022",
      },
    ],
    clothingSizes: {
      height: "183 см",
      chest: "100 см",
      waist: "86 см",
      shoes: "43",
      headgear: "58",
      uniform: "48/3",
    },
    positionHistory: [
      {
        position: "Начальник розвідки",
        unit: "3-тя штурмова бригада",
        startDate: "01.2024",
      },
      {
        position: "Заступник начальника розвідки",
        unit: "3-тя штурмова бригада",
        startDate: "03.2021",
        endDate: "01.2024",
      },
      {
        position: "Старший розвідник",
        unit: "3-тя штурмова бригада",
        startDate: "04.2018",
        endDate: "03.2021",
      },
      {
        position: "Розвідник",
        unit: "3-тя штурмова бригада",
        startDate: "09.2014",
        endDate: "04.2018",
      },
    ],
  },
];
